site_name: Aerobox Games
site_url: https://aeroboxgames.com

nav:
  - Games: index.md
  - Element X: element-x.md
  - Rogue Racer: rogue-racer.md

theme:
  name: material
  palette:
    scheme: slate
    primary: black
  font:
    text: Roboto

  logo: assets/logo.png
  favicon: assets/logo.png

  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky

plugins:
  - blog

extra:
  # generator: false
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/aeroboxgames
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/aeroboxgames?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==
    - icon: fontawesome/brands/discord
      link: https://www.instagram.com/aeroboxgames?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==
  generator: false

extra_css:
  - stylesheets/extra.css
  - stylesheets/main-page.css
  - stylesheets/element-x.css

extra_javascript:
  - javascripts/extra.js
  - javascripts/element-x.js

copyright: Copyright &copy; 2020 - 2026 Aerobox Games.
